### ISSUE TITLE
Provisioning failure "List 'Document Types' does not exist " on Atvero Hub

### ISSUE THREAD

**Issue by jim80** [nittygritty-uk/Atvero-Issues#447]
2019-04-09T09:00:47: Updating List Document Types in https://atverodev.sharepoint.com/sites/JH05
2019-04-09T09:00:49: Finished working on List Document Types in https://atverodev.sharepoint.com/sites/JH05
2019-04-09T09:00:49: Copying document types and quick parts
2019-04-09T09:00:49: AtveroHub
2019-04-09T09:00:49: Exception caught - provisioing failed
2019-04-09T09:00:49: List 'Document Types' does not exist at site with URL 'https://atverodev.sharepoint.com/sites/AtveroHub'.
2019-04-09T09:00:49:    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()

**Comment by allanchaplin** [comment]
Give Jim permissions to see the Document Types List in the hub
